spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:sampletest;MODE=MySQL

  datasource:
    driverClassName: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/dingo
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false

spring.jpa:
    hibernate:
      ddl-auto: create